import { Inter } from 'next/font/google'
import "./globals.css";
import { Toaster } from "react-hot-toast";
import RootLayoutClient from "./RootLayoutClient";

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
})
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Toaster
          position="right-bottom"
          reverseOrder={false}
        />
            <div className={`${inter.variable} bg-white`}>
              <RootLayoutClient>{children}</RootLayoutClient>
            </div>
      </body>
    </html>
  );
}
